# Generated by Django 2.1.7 on 2019-03-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='article',
        ),
        migrations.AlterField(
            model_name='article',
            name='analysed_at',
            field=models.DateTimeField(blank=True, verbose_name='date article classified'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
