# Generated by Django 2.1.7 on 2019-03-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0002_auto_20190313_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pub_date',
            new_name='published_at',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='analysed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date article classified'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='label',
            field=models.CharField(blank=True, choices=[('0', 'NEGATIVE'), ('1', 'POSITIVE'), ('2', 'NEUTRAL')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
